---
name: WebService-HtmlKitCom-FavIconFromImage
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: generate favicons from images on http://www.html-kit.com/favicon/
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  Devel::TakeHashArgs: 0.002
  WWW::Mechanize: 1.34
build_requires:
  Test::More: 0
provides:
  WebService::HtmlKitCom::FavIconFromImage:
    file: lib/WebService/HtmlKitCom/FavIconFromImage.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
